{"uuid": "40b845c1-d2f9-4681-9d5a-a3fd587b8e0b", "children": ["06faf9bd-42a6-44a7-9bd4-b98325ecaf90"], "befores": [{"name": "_xunit_setup_method_fixture_TestDept", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nBacktrace:\n\tOrdinal0 [0x003B9943+2595139]\n\tOrdinal0 [0x0034C9F1+2148849]\n\tOrdinal0 [0x00244528+1066280]\n\tOrdinal0 [0x00270FD4+1249236]\n\tOrdinal0 [0x002711CB+1249739]\n\tOrdinal0 [0x0029D812+1431570]\n\tOrdinal0 [0x0028BA34+1358388]\n\tOrdinal0 [0x0029BAF2+1424114]\n\tOrdinal0 [0x0028B806+1357830]\n\tOrdinal0 [0x00266086+1204358]\n\tOrdinal0 [0x00266F96+1208214]\n\tGetHandleVerifier [0x0055B232+1658114]\n\tGetHandleVerifier [0x0061312C+2411516]\n\tGetHandleVerifier [0x0044F261+560433]\n\tGetHandleVerifier [0x0044E366+556598]\n\tOrdinal0 [0x0035286B+2173035]\n\tOrdinal0 [0x003575F8+2192888]\n\tOrdinal0 [0x003576E5+2193125]\n\tOrdinal0 [0x003611FC+2232828]\n\tBaseThreadInitThunk [0x76C86BD9+25]\n\tRtlGetFullPathName_UEx [0x77D58FD2+1218]\n\tRtlGetFullPathName_UEx [0x77D58F9D+1165]\n\n", "trace": "  File \"C:\\Users\\琪琪\\AppData\\Local\\Programs\\Python\\Python39-32\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\琪琪\\AppData\\Local\\Programs\\Python\\Python39-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\琪琪\\AppData\\Local\\Programs\\Python\\Python39-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\琪琪\\AppData\\Local\\Programs\\Python\\Python39-32\\lib\\site-packages\\_pytest\\python.py\", line 893, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\琪琪\\AppData\\Local\\Programs\\Python\\Python39-32\\lib\\site-packages\\_pytest\\python.py\", line 778, in _call_with_optional_argument\n    func()\n  File \"D:\\MyGit\\Api_test\\test\\UI_test\\case\\test_03_dept.py\", line 29, in setup\n    self.dept.switch_to_main_frame()\n  File \"D:\\MyGit\\Api_test\\test\\UI_test\\page\\department.py\", line 51, in switch_to_main_frame\n    ele_mode_sys = self.wait_ele_visible(self.loc_mode_sys, doc=\"定位系统模块\")\n  File \"D:\\MyGit\\Api_test\\test\\UI_test\\base\\base.py\", line 139, in wait_ele_visible\n    ele = WebDriverWait(self.driver, timeout).until(EC.visibility_of_element_located(locator))\n  File \"C:\\Users\\琪琪\\AppData\\Local\\Programs\\Python\\Python39-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1679540491182, "stop": 1679540502955}], "start": 1679540491182, "stop": 1679540502966}