{"name": "test_file_upload", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'D:/MyGit/img/01c8f15aeac135a801207fa16836ae.jpg@1280w_1l_2o_100sh.jpg'", "trace": "self = <test_login.TestSendRequest object at 0x000001C89A3D4B50>\nconn_database = None\n\n    @pytest.mark.smoke\n    def test_file_upload(self,conn_database):\n        url = 'https://jxh-api.zx1026.com//Common/Upload/file'\n        headers = {\n            'token':YamlUtil().read_extract_yaml('token'),\n        \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36 Edg/110.0.1587.41\",\n        }\n        data={\n>           \"file\" : open(\"D:/MyGit/img/01c8f15aeac135a801207fa16836ae.jpg@1280w_1l_2o_100sh.jpg\", 'rb')\n        }\nE       FileNotFoundError: [Errno 2] No such file or directory: 'D:/MyGit/img/01c8f15aeac135a801207fa16836ae.jpg@1280w_1l_2o_100sh.jpg'\n\ntest_login.py:53: FileNotFoundError"}, "attachments": [{"name": "stdout", "source": "2f5fd2a4-f49b-48f9-b6c3-94adae67af72-attachment.txt", "type": "text/plain"}], "start": 1676821599659, "stop": 1676821599660, "uuid": "37515b07-2cdb-42da-a5d1-8dcdfc33c5dc", "historyId": "6e55fb0cb4de8d47e266dbd20a66bbcd", "testCaseId": "0cfe7cbaa0b355ca19f1a9d8385c2d8a", "fullName": "testcases.test_login.TestSendRequest#test_file_upload", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestSendRequest"}, {"name": "host", "value": "LAPTOP-9995G3A1"}, {"name": "thread", "value": "18876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}